// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// keyWRU_fit
Rcpp::List keyWRU_fit(Rcpp::List data, Rcpp::List ctrl);
RcppExport SEXP _wru_keyWRU_fit(SEXP dataSEXP, SEXP ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type ctrl(ctrlSEXP);
    rcpp_result_gen = Rcpp::wrap(keyWRU_fit(data, ctrl));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wru_keyWRU_fit", (DL_FUNC) &_wru_keyWRU_fit, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_wru(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
