# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Collapsed Gibbs sampler for keyWRU
#'
#' @param data A list with the following elements
#' @param ctrl A list of control arguments, including
#'
#' @keywords internal
keyWRU_fit <- function(data, ctrl) {
    .Call('_wru_keyWRU_fit', PACKAGE = 'wru', data, ctrl)
}

